### PR TITLE
Use sox as alternate audio input.

### PR DESCRIPTION
**Pull request by tpoindex**
This patch is useful on systems that normally don't install PulseAudio - FreeBSD for one., probably some Linux systems as well.

### CODE REVIEW

**Comment by ideasman42** [comment]
Thanks for the patch, in general this seems fine.

Could you update this patch to follow the convention for output?

See `nerd-dictation begin --help` there is `--output OUTPUT_METHOD` ... `SIMULATE_INPUT` `STDOUT`.

An equivalent would be `--input` options could be `PAREC`, `SOX` ... etc.

This means if MS-Windows or macOS support is added we don't end up with too many top-level arguments that don't make sense on other systems.

**Comment by tpoindex** [comment]
Changed --sox to --input-method, along with arg parsing, readme.
Perhaps this is closer to what you have in mind.

**Comment by ideasman42** [comment]
Looks good, would you mind changing `--input-method CMD` to `--input INPUT_METHOD`  ?

This way the `--input` command matches the `--output` command and is easier to remember.

**Comment by tpoindex** [comment]
Done.  I actually had this one my previous edit, but didn't like how the --help text was formatted :-)

**Comment by tpoindex** [comment]
Thx, missed that.

**Comment by ideasman42** [comment]
Thanks, Committed a574dddb422010389c2f3a5cd84ed685738b7a4c

Before pushing I noticed some minor changes (capitalize choices matching input & black formatter needed to be run).

Made the changes and committed.

**Pull request closed without merging**
