### PR TITLE
papoteur-mga's Pynput method, but it detects if xdotool is installed and working

### PR DESCRIPTION
**Pull request by ForrestHilton**

### CODE REVIEW

**Comment by ForrestHilton** [comment]
I tested this on both x11 and wayland, and pynput works on both. I prefer pynput on both because it does backspaces faster.

**Review by ideasman42 — CHANGES_REQUESTED** [review]
- Pressing backspace with pynput doesn't look correct, it's only pressing once, where xdotool backspaces the length of entered text.
- I would prefer `pynput` have a separate block instead of adding input method checks inside nested if-checks. Even if this adds a little bit of duplicate code - since adding more methods will become difficult to read.

**Comment by ForrestHilton** [comment]
I think this is ready for another look.

**Comment by ForrestHilton** [comment]
There is a bug in the pull request, that I can't fix tonight (US time). I think that the keyboard events are getting out of order sometimes.

Also I couldn't help but notice that text_block is always 1 long if it starts with \x08, so there was no need to iterate over the blocs length.

**Comment by ForrestHilton** [comment]
It turns out that under the hood pynput is using its xorg backend. This means that it will not do any better than xdotool. Simply compiling or downloading a [different version of xdotool](https://github.com/jordansissel/xdotool/issues/346) that doesn't disable xwayland will achieve a better results than I have thus far gotten with pynput. 

The fact that nerd dictation types faster using pynput than xdotool is basically a bug and causes keys to be processed out of order by some applications. In order to make pynput work correctly, I would need to adjust the timing between each key. I don't plan to do this as it would give no advantage over xdotool.

Although almost all applications on my computer apparently use xwayland, several gtk applications don't, and they do not receive keys. 

The intended alternative to x based typing is uinput, which is like a Linux driver. Though there is a uinput backend in pynput, I haven't gotten it to work. The only thing that I have gotten to work is a [c script](https://github.com/piater/uinputchars), but it always emits a trailing new line. 

I am still hoping that I can get pynput to work with uinput, but that presents issues because uinput requires root privileges.

**Comment by ForrestHilton** [comment]
[ydotool](https://github.com/ReimuNotMoe/ydotool) is the obvious replacement, and it works. Its clear from the readme that pynput is unlikely to ever work as well as ydotool. In our use case ydotool will need setuid privileges. Another drawback is that it needs a damon to work consistently.

I plan to add it to this pull request.

**Comment by ForrestHilton** [comment]
I'm sorry for making promises that I couldn't keep. I will not be doing any more follow-up. I am no longer using nerd dictation.

**Comment by sssstable** [comment]
@copilot Devcontainer Build: Authenticated Services, Ollama Model Check, Remove OPSD 

 --- 

 This pull request implements the following changes:

- On every build of the devcontainer, services such as Google authentication and Supabase are now correctly authenticated using the appropriate credentials. This ensures automated authentication flows during container startup.

- A check has been added to confirm which Ollama model is available and provide that confirmation in the build logs.

- All references to OPSD have been removed, as these are no longer required.

These changes should streamline the development container builds and ensure that service integrations work as expected.

**Pull request closed without merging**
