### PR TITLE
Propose an alternative method to simulate input, using pynput

### PR DESCRIPTION
**Pull request by papoteur-mga**
A new option --simulate-input-method is added.
This replaces xdotool and needs pynput as new module.
See #4

### CODE REVIEW

**Comment by ideasman42** [comment]
Looks good, see notes on https://github.com/ideasman42/nerd-dictation/blob/master/hacking.rst
- Auto-formatter neeeds to be run `black nerd-dictation`
- mypy is reporting errors `# type: ignore` is needed for the unknown import.

**Comment by papoteur-mga** [comment]
Thanks for your comment.
Adding the comment ` type: ignore` doesn't help to pass the test. This is explicitly ignored.
But what is bad, is that this method suffers the same default as xdotool. This was masked in my tests because I had done setxkbmap before. After a reboot, I was nuked.

**Comment by ideasman42** [comment]
Note that an alternative to this could be to use copy/paste, although the down side for this is it will likely overwrite the current buffer.
Although it's possible to backup/restore that it may not behave well with clipboard managers.

---

Note that X11 may be on the way out in favor of Wayland, if there are no good solutions this could simply be documented as a known issue with instructions for working around it.

**Comment by jgyllinsky** [comment]
> An alternative to this could be to use copy/paste, although the down side for this is it will overwrite the current paste buffer.
> Although it's possible to backup/restore that it may not behave well with clipboard managers.
> 
> Note that X11 may be on the way out in favor of Wayland

This may especially not be the case on non-x86 cpu architectures.

**Comment by ideasman42** [comment]
Seeing as ydotool is now supported, which works well for X11 and Wayland, I'd rather stick to these two tools and don't see tangible benefits of pynput.

**Pull request closed without merging**
