### PR TITLE
Add lexicon graph JSON support

### PR DESCRIPTION
**Pull request by KJ7LNW**
This is a native Vosk feature so enablement was pretty simple.  See commit and code comments for detail.

### CODE REVIEW

**Review by ideasman42 — CHANGES_REQUESTED** [review]
Please ensure this gives no warnings with:

`mypy --strict nerd-dictation`.

Use `black nerd-dictation` to format the code.

----

- `vosk_grammar_file` could default to "" instead of None, for simplicity.
- Same for `grammar_json`

**Review by ideasman42 — CHANGES_REQUESTED** [review]
`if vosk_grammar_file is not None:` no longer makes sense. Same for any other comparisons with None.

**Comment by KJ7LNW** [comment]
Hi @ideasman42 ,

This is now rebased on top of `main` after merging #85 and squashed the str/None fixes, so the commits are more readable.  Now this has only the two commits to ease review.

**Comment by ideasman42** [comment]
Hey @KJ7LNW, this looks really interesting, I don't have time just now to review but the feature looks good an I think it's fine to be included.

**Pull request merged**
