### PR TITLE
command line options, suspend via signal

### PR DESCRIPTION
**Pull request by KJ7LNW**
Hello Campbell,

Thank you for writing this package! It has saved my ability to type and communicate effectively with others without the need to dictate to someone else while writing emails!

Please consider this series of minor changes that have made it easier for me to dictate business emails because I cannot type the way I used to. They are all core changes that would be difficult or impossible to implement in the user config.

These are all backwards compatible with the exception of c8dd75d which moves numerical processing before calling the user config function because it is easier to process numbers after they have been converted. If you think that it would be better to have an option for this, then let me know, but I'm guessing that this is helpful to others as well.

Please review the commit descriptions for detail.

-Eric

### CODE REVIEW

**Comment by ideasman42** [comment]
Hi Eric, thanks for the excellent PR, with some of the larger (higher quality) language models pausing is useful.

**Comment by KJ7LNW** [comment]
You're welcome!  I've been using the `vosk-model-en-us-0.42-gigaspeech` model and it works amazingly well: accurate and fast... but it takes 30-60 seconds to load, so yeah, pausing is a must!  

This is my invocation, then I just press `enter` to pause/resume in the terminal:

```sh
nerd-dictation begin --punctuate-from-previous-timeout=2 --numbers-as-digits --idle-time 0.3 --numbers-min-value=3 --numbers-no-suffix & 

while read a; do pkill -USR1 -f python.*nerd; done
```

**Comment by KJ7LNW** [comment]
I like your changes to come particularly the fact that you are closing `parec` during suspend and starting it back up on resume.

I tried your latest release and I get this error (not sure if I should open an issue because this is related to the recent changes noted above):

```py
File "./nerd-dictation", line 248
    simulate_typing_with_dotool_proc: Optional[subprocess.Popen[str]] = None
    ^
SyntaxError: annotated name 'simulate_typing_with_dotool_proc' can't be global
```

If I revert line 248:
```
-simulate_typing_with_dotool_proc: Optional[subprocess.Popen[str]] = None
+simulate_typing_with_dotool_proc = None
```
then I get this:

```py
Traceback (most recent call last):
  File "./nerd-dictation", line 845, in <module>
    ) -> Tuple[subprocess.Popen[bytes], IO[bytes]]:
TypeError: 'type' object is not subscriptable
```

Do you know what needs to be fixed? I am running python 3.6.8.

**Comment by ideasman42** [comment]
Python 3.6x was released in 2016 and is end-of-file, (no longer getting security fixes), see https://devguide.python.org/versions/ so I think it would be reasonable to drop support for it too.

Resolved fd71a9aa04acd70b1884f16cecd3d3994e1c4031 for now though.

**Comment by ideasman42** [comment]
I was thinking the following changes and interested in your thoughts:

- Add sub-commands, `nerd-dictation suspend` & `nerd-dictation resume` - so it's not necessary for the user to send signals and search for sub-processes.
- Add support for starting suspended, e.g. `nerd-dictation begin --suspend`.
- Remove `USR1` as a toggle, replace with `nerd-dictation suspend --toggle` for e.g.

**Comment by KJ7LNW** [comment]
> Python 3.6x was released in 2016 and is end-of-file

ok. Thanks for fixing it!  RHEL7/CentOS7 still uses it, which I have on my desk for a bit longer...

> I was thinking the following changes and interested in your thoughts:
> 
> * Add sub-commands, `nerd-dictation suspend` & `nerd-dictation resume` - so it's not necessary for the user to send signals and search for sub-processes.
> 
> * Add support for starting suspended, e.g. `nerd-dictation begin --suspend`, to make it convenient to start nerd-dictation as a service.
> 
> * Remove `USR1` as a toggle, replace with `nerd-dictation suspend --toggle` for e.g.

Definitely!  Since you will be handling process communication, it would be nice to prevent running the background recording process ("begin") more than once by accident, too.

**Comment by KJ7LNW** [comment]
Other related --options that would be nice:
1.  --suspend-timeout: Auto suspend after inactivity
2.  --recording-timeout: Auto reset recording and dictation state after inactivity. This would be useful because sometimes I just speak short sentence fragments when editing a document, but those fragments are unrelated so it confuses the engine and sometimes makes strange corrections. I have wanted a feature to `rec.Reset()` and `text_prev` after about 3 to 5 seconds but have not looked into creating an option for it yet. if there is already an option that does this then please point it out. I think that would simply call the following:
    - rec.Reset()
    - handle_fn_suspended()

 by the way, is there a reason that `rec.Reset()` is not included in `handle_fn_suspended()` ? I sort of think there should be a single function to clear all recording state in the program.

**Comment by ideasman42** [comment]
`--suspend-timeout` not sure about this, it means the user needs to manually resume (not against, I'd prefer to have `nerd-dictation suspend/resume` working well before testing out other features).

`--recording-timeout` seems fine & non-controversial.

---

Neither `handle_fn_suspended` not `handle_fn_wrapper` operate on `rec.*` directly, for now I'd rather keep it this way, ... it seems likely this area could be refactored later but I rather do this after having suspend/resume sub-commands working.

**Comment by KJ7LNW** [comment]
> `--suspend-timeout` it means the user needs to manually resume

True, or in my case, `suspend --toggle` which would work in either state.

> (not against, I'd prefer to have `nerd-dictation suspend/resume` working well before testing out other features).

cool, no hurry.


> Neither handle_fn_suspended not handle_fn_wrapper operate on rec.* directly, for now I'd rather keep it this way so the VOSK handling isn't happening in both the main-loop and in nested functions, ... it seems likely this area could be refactored later but I rather do this after having suspend/resume sub-commands working.

sounds fine, not concerned about the details there.

**Comment by ideasman42** [comment]
Note that `suspend/resume` and `--suspend-on-start` are now supported, interested to know if these work well for your use-case.

**Comment by KJ7LNW** [comment]
Tried it:

```py
# ./nerd-dictation begin --suspend-on-start --punctuate-from-previous-timeout=2 --numbers-as-digits --idle-time 0.3 --numbers-min-value=3 --numbers-no-suffix 

Traceback (most recent call last):
  File "./nerd-dictation", line 1832, in <module>
    main()
  File "./nerd-dictation", line 1828, in main
    args.func(args)
  File "./nerd-dictation", line 1715, in <lambda>
    suspend_on_start=args.suspend_on_start,
  File "./nerd-dictation", line 1342, in main_begin
    suspend_on_start=suspend_on_start,
  File "./nerd-dictation", line 1090, in text_from_vosk_pipe
    signal.raise_signal(signal.SIGSTOP)
AttributeError: module 'signal' has no attribute 'raise_signal'
```

**Comment by ideasman42** [comment]
This should be resolved now.

**Pull request merged**
